# Generated by Django 6.0.1 on 2026-01-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='amount',
            new_name='guests',
        ),
    ]
