# Generated by Django 6.0.1 on 2026-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_amount_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_service',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='smoke_service',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
