# Generated by Django 6.0.1 on 2026-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_banner_service_alter_event_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('worker_type', models.CharField(choices=[('chefs', 'Chefs'), ('musicians', 'Musicians'), ('waiters', 'Waiters'), ('dishwashers', 'Dishwashers'), ('florewashers', 'Floor Washers'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
